export const PARTIAL_HIDE = 'PARTIAL_HIDE';
export type PARTIAL_HIDE = typeof PARTIAL_HIDE;

export const FULL_HIDE = 'FULL_HIDE';
export type FULL_HIDE = typeof FULL_HIDE;

export const ADD_DOMAIN = 'ADD_DOMAIN';
export type ADD_DOMAIN = typeof ADD_DOMAIN;

export const FETCH_DOMAINS = 'FETCH_DOMAINS';
export type FETCH_DOMAINS = typeof FETCH_DOMAINS;

export const FETCH_DOMAINS_PENDING = 'FETCH_DOMAINS_PENDING';
export type FETCH_DOMAINS_PENDING = typeof FETCH_DOMAINS_PENDING;

export const FETCH_DOMAINS_FULFILLED = 'FETCH_DOMAINS_FULFILLED';
export type FETCH_DOMAINS_FULFILLED = typeof FETCH_DOMAINS_FULFILLED;

export const FETCH_DOMAINS_REJECTED = 'FETCH_DOMAINS_REJECTED';
export type FETCH_DOMAINS_REJECTED = typeof FETCH_DOMAINS_REJECTED;

export const REMOVE_DOMAIN = 'REMOVE_DOMAIN';
export type REMOVE_DOMAIN = typeof REMOVE_DOMAIN;

export const MENAGE_ANIMATIONS = 'MENAGE_ANIMATIONS';
export type MENAGE_ANIMATIONS = typeof MENAGE_ANIMATIONS;
