export const HIGHLIGHT = 'HIGHLIGHT';
export type HIGHLIGHT = typeof HIGHLIGHT;

export const PARTIAL_HIDE = 'PARTIAL_HIDE';
export type PARTIAL_HIDE = typeof PARTIAL_HIDE;

export const FULL_HIDE = 'FULL_HIDE';
export type FULL_HIDE = typeof FULL_HIDE;

export const COLOR_1 = 'COLOR_1';
export type COLOR_1 = typeof COLOR_1;

export const COLOR_2 = 'COLOR_2';
export type COLOR_2 = typeof COLOR_2;

export const COLOR_3 = 'COLOR_3';
export type COLOR_3 = typeof COLOR_3;

export const ADD_DOMAIN = 'ADD_DOMAIN';
export type ADD_DOMAIN = typeof ADD_DOMAIN;

export const FETCH_DOMAINS = 'FETCH_DOMAINS';
export type FETCH_DOMAINS = typeof FETCH_DOMAINS;

export const FETCH_DOMAINS_PENDING = 'FETCH_DOMAINS_PENDING';
export type FETCH_DOMAINS_PENDING = typeof FETCH_DOMAINS_PENDING;

export const FETCH_DOMAINS_FULFILLED = 'FETCH_DOMAINS_FULFILLED';
export type FETCH_DOMAINS_FULFILLED = typeof FETCH_DOMAINS_FULFILLED;

export const FETCH_DOMAINS_REJECTED = 'FETCH_DOMAINS_REJECTED';
export type FETCH_DOMAINS_REJECTED = typeof FETCH_DOMAINS_REJECTED;

export const REMOVE_DOMAIN = 'REMOVE_DOMAIN';
export type REMOVE_DOMAIN = typeof REMOVE_DOMAIN;

export const MENAGE_ANIMATIONS = 'MENAGE_ANIMATIONS';
export type MENAGE_ANIMATIONS = typeof MENAGE_ANIMATIONS;

export const IMPORT_FROM_OLD_VERSION = 'IMPORT_FROM_OLD_VERSION';
export type IMPORT_FROM_OLD_VERSION = typeof IMPORT_FROM_OLD_VERSION;

export const IMPORT_FROM_OLD_VERSION_PENDING = 'IMPORT_FROM_OLD_VERSION_PENDING';
export type IMPORT_FROM_OLD_VERSION_PENDING = typeof IMPORT_FROM_OLD_VERSION_PENDING;

export const IMPORT_FROM_OLD_VERSION_FULFILLED = 'IMPORT_FROM_OLD_VERSION_FULFILLED';
export type IMPORT_FROM_OLD_VERSION_FULFILLED = typeof IMPORT_FROM_OLD_VERSION_FULFILLED;

export const IMPORT_FROM_OLD_VERSION_REJECTED = 'IMPORT_FROM_OLD_VERSION_REJECTED';
export type IMPORT_FROM_OLD_VERSION_REJECTED = typeof IMPORT_FROM_OLD_VERSION_REJECTED;
